### ISSUE TITLE
Cmake Error

### ISSUE THREAD

**Issue by fbi-ranger** [SDL-Hercules-390/SoftFloat#6]
I cannot build SoftFloat: 

cmake fails with following error:

CMake Error at cmake/modules/ParseBinaryDir.cmake:129 (message):
  Invalid package architecture! fh

Call Stack (most recent call first):
  CMakeLists.txt:50 (ParseBinaryDir)

BR Florian

**Comment by wrljet** [comment]
Could you tell us the exact steps you used.

**Comment by fbi-ranger** [comment]
Sorry! My fault. I checked my script and encountered that I used an old version. 
The right one works. Sorry for the inconvenience. 

BR Florian
