### ISSUE TITLE
float16_t, float32_t,  float64_t, float128_t typedefs clashes 

### ISSUE THREAD

**Issue by ghost** [SDL-Hercules-390/SoftFloat#7]
the typedefs float16_t, float32_t,  float64_t, float128_t in softfloat_types.h clash 
with the corresponding typedefs in the system header arm_neon.h

this clash prevents the implementation of the arm neon intrinsics

the solution is pretty simple.... 
change floatxxx_t to something like softfloat_floatxxx_t/SFLT_floatxxx_t

with a smart editor the change can be done in couple of minutes
BTDTGTTS

done and working in my private repo

 posted also into the hyperion repository

**Comment by Fish-Git** [comment]
Issue being discussed and handled in the main Hercules repository's GitHub Issue #675 topic:

* https://github.com/SDL-Hercules-390/hyperion/issues/675

Closing THIS issue.
